#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
sudo echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 54.173.84.39:80
        server 64820-web-02 100.25.183.235:80
' >> sudo /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart

