#!/usr/bin/env bash
# This script is displaying The content of the current directory Where only the part of the name after the first dash is displayed
f="school"

if [ -e "$f" ]
then
    echo "school file exists"
    if [ ! -s "$f" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$f" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
